version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"
    networks:
     - "monitoring-lab"
    volumes:
     - "grafana_data:/var/lib/grafana"
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
     - "5000:80"
     - "8125:8125/udp"
     - "8126:8126"
     - "2003:2003"
     - "2004:2004"
    networks:
     - "monitoring-lab"
    volumes:
     - "graphite_data:/opt/graphite/storage/whisper"
  app:
    image: selaworkshops/npm-static-app
    container_name: app
    restart: always
    ports:
     - "80:3000"
    networks:
     - "monitoring-lab"
networks:
  monitoring-lab:
volumes:
  grafana_data:
  graphite_data:
